rwahs/installation-profile

- .editorconfig
- .gitignore
- base_en_AU.xml
- remove-locales.xslt
- rwahs.xml
* includes xslt to generate a base profile with only en_AU locale
> Add first cut at RWAHS installation profile

- rwahs.xml
https://youtrack.gaiaresources.com.au/issue/RWAHS-34
> correct idno for photograph, add legacyId field to profile, add preferred_labels to the museum object editor

- .editorconfig
- remove-locales.xslt
- rwahs.xml
Installation Profile for `itemData`
> Rwahs 52/item data

- rwahs.xml
* The previous `render` value was incorrect - that is for a single checkbox
* Also bump the maxAttributesPerRow to the commonly used one
* set `<setting name="maxColumns">6</setting>` so checkboxes are 6 in a row
> Use `checklist` for `SignificanceCriteria` and `ComparativeCriteria`

- rwahs.xml
Schema and editor for the subject list
> Rwahs 69/import subject list

- rwahs.xml
> Use `<ifdef/>` for related occurrences template

- profile/rwahs.xml
* Storage locations need to now use the ca_movements location tracking mode
> Fix storage location contents listing

- profile/rwahs.xml
* Additional storage location types
* Fix template for storage locations related to the relevant movements
> Rwahs 50/storage location contents

- profile/rwahs.xml
includes #15 so that should be merged first.
> Rwahs 78/object representation on item data screen

- profile/rwahs.xml
* standardise width and height of wysiwyg fields
* Text fields use medium text max length (rather
* single row for LastEditBy and AccessionBy
> Minor tweaks to ui for fields

- profile/profile.xsd
- profile/rwahs.xml
- tests/Profile/ProfileACLTest.php
- tests/Profile/ProfileElementTest.php
- tests/Profile/ProfileUiTest.php
Add form for library records
* Role for library users
* Group for library users
* Tests for editor access
* Tests to further validate the profile
> Rwahs 114/library form

- profile/rwahs.xml
- tests/Profile/ProfileElementTest.php
* Also use CamelCase for library PublicationType
We still need to hear about placement of these bundles
> Add missing library fields into the data model

- profile/rwahs.xml
> make series attribute an integer and free of locale

- profile/rwahs.xml
- tests/Profile/LibraryProfileTest.php
* Additionally set Integer values to all be a maximum of 11 characters long
> Add missing library storage locations

- profile/rwahs.xml
> Museum form

- profile/rwahs.xml
- profile/searchFormsMicroprofile.xml
* Fix issue with missing donor field on museum search form
* Add microprofile to add search forms
> Microprofile for search forms

- profile/searchFormsMicroprofile.xml
* Don't add superfluous records.
> Remove the extra `base` component from microprofile

- profile/rwahs.xml
- transforms/derive-displays.xslt
https://gaiaresources.myjetbrains.com/youtrack/issue/RWAHS-202
> Derive displays for all base data types

- profile/rwahs.xml
- tests/Profile/ProfileElementTest.php
Contains #39 and that should be merged first.
* Change Creator to a Container with Creator Type and Creator Name inside it
* Fix list element tests not checking all list elements
-  We were not covering list elements within containers
- Add checks such that requireValue and nullOptionText have corresponding values
* add missing settings and lists
- DimensionsType list with two values matching the requirements document
- Add requireValue = 0 to List elements that have nullOptionText set
- or remove nullOptionText for checkbox elements
> RWAHS-209/creator field changes

- profile/rwahs.xml
Includes #42 and that should be merged first.
> RWAHS-151 Move library images to before review field

- profile/rwahs.xml
> RWAHS-199 - public memorials - add references field to form

- profile/rwahs.xml
includes #44, adds a media element to condition reports
> Rwahs 135/forms   museum   add media to condition report

- profile/rwahs.xml
- tests/Profile/ProfileACLTest.php
> Add web service user and role to profile

- profile/rwahs.xml
- transforms/derive-displays.xslt
+ Modify XSLT.
+ Fix formatting in XSLT (unrelated).
+ Update profile XML file with the result (some minor manual tweaks relating to CDATA sections).
> Derive type restrictions for derived displays from their source UI.

- profile/rwahs.xml
> Rwahs 128/search form   photographs

- profile/rwahs.xml
Add Dimensions to photographs UI and display
Rename Copyright Holder to Copyright Details
> Rwahs 296/photographs fields tidyup

- profile/rwahs.xml
* Also add restrictions and group access permissions for library and museum search displays
* whitespace reformatting
> Add memorial and photograph search displays

- profile/rwahs.xml
> Add correct type restriction to public memorial search display

- profile/rwahs.xml
- transforms/derive-displays.xslt
* Change xslt to copy these access permissions
* Update profile with these new derived values
* Also add missing groupAccess for the `subject_list_ui`
> Fix RWAHS-443 Copy `groupAccess` from ui into derived displays

- profile/rwahs.xml
#61 was from my master branch. oops. Anyway this is now from a real branch
* And in generated display
> RWAHS-347 Add "access" placement on Public Memorials form

- profile/rwahs.xml
* This value is now prepopulated
> RWAHS-136: Remove preferred_labels from conservation editor

- profile/rwahs.xml
goes with https://github.com/rwahs/providence-configuration/pull/36
Includes #66
> Rwahs 476/add representation display

- profile/rwahs.xml
- tests/Profile/ProfileElementTest.php
* Ensure that the `render` is set for list attribute types
* Ensure that the `requireValue` is set for list attribute types
* RWAHS-293
> Make all list attributes optional

- profile/rwahs.xml
- tests/Profile/AbstractProfileTest.php
- tests/Profile/ProfileACLTest.php
* These changes have been applied on UAT.
> RWAHS-486 Remove delete and other administrative permissions from cataloguers
